name: Products CD Pipeline

# on:
#   workflow_run:
#     workflows: ["Products CI Pipeline"]
#     types:
#       - completed

on:
  workflow_dispatch:

jobs:

  build:

    runs-on: [self-hosted, linux, x64, product-runner]

    steps:
    - name: Pull Docker image
      run: sudo docker pull sivakumar2905/products:latest
    - name: Delete Old docker container
      run: sudo docker rm -f products-container || true
    - name: Run Docker Container
      run: sudo docker run -d -p 4002:4002 --name products-container sivakumar2905/products:latest