name: Users CD Pipeline

on:
  workflow_run:
    workflows: ["Users CI Pipeline"]
    types:
      - completed

jobs:

  build:

    runs-on: self-hosted[users]

    steps:

    - name: Pull Docker image
      run: sudo docker pull sivakumar2905/users:latest
    - name: Delete Old docker container
      run: sudo docker rm -f users-container || true
    - name: Run Docker Container
      run: sudo docker run -d -p 4001:4001 --name users-container sivakumar2905/users:latest